// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/shirasudon/go-chat/chat (interfaces: UserQueryer,RoomQueryer,MessageQueryer,EventQueryer)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	queried "github.com/shirasudon/go-chat/chat/queried"
	domain "github.com/shirasudon/go-chat/domain"
	event "github.com/shirasudon/go-chat/domain/event"
	reflect "reflect"
	time "time"
)

// MockUserQueryer is a mock of UserQueryer interface
type MockUserQueryer struct {
	ctrl     *gomock.Controller
	recorder *MockUserQueryerMockRecorder
}

// MockUserQueryerMockRecorder is the mock recorder for MockUserQueryer
type MockUserQueryerMockRecorder struct {
	mock *MockUserQueryer
}

// NewMockUserQueryer creates a new mock instance
func NewMockUserQueryer(ctrl *gomock.Controller) *MockUserQueryer {
	mock := &MockUserQueryer{ctrl: ctrl}
	mock.recorder = &MockUserQueryerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserQueryer) EXPECT() *MockUserQueryerMockRecorder {
	return m.recorder
}

// Find mocks base method
func (m *MockUserQueryer) Find(arg0 context.Context, arg1 uint64) (domain.User, error) {
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *MockUserQueryerMockRecorder) Find(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockUserQueryer)(nil).Find), arg0, arg1)
}

// FindUserRelation mocks base method
func (m *MockUserQueryer) FindUserRelation(arg0 context.Context, arg1 uint64) (*queried.UserRelation, error) {
	ret := m.ctrl.Call(m, "FindUserRelation", arg0, arg1)
	ret0, _ := ret[0].(*queried.UserRelation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserRelation indicates an expected call of FindUserRelation
func (mr *MockUserQueryerMockRecorder) FindUserRelation(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserRelation", reflect.TypeOf((*MockUserQueryer)(nil).FindUserRelation), arg0, arg1)
}

// MockRoomQueryer is a mock of RoomQueryer interface
type MockRoomQueryer struct {
	ctrl     *gomock.Controller
	recorder *MockRoomQueryerMockRecorder
}

// MockRoomQueryerMockRecorder is the mock recorder for MockRoomQueryer
type MockRoomQueryerMockRecorder struct {
	mock *MockRoomQueryer
}

// NewMockRoomQueryer creates a new mock instance
func NewMockRoomQueryer(ctrl *gomock.Controller) *MockRoomQueryer {
	mock := &MockRoomQueryer{ctrl: ctrl}
	mock.recorder = &MockRoomQueryerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRoomQueryer) EXPECT() *MockRoomQueryerMockRecorder {
	return m.recorder
}

// Find mocks base method
func (m *MockRoomQueryer) Find(arg0 context.Context, arg1 uint64) (domain.Room, error) {
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(domain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *MockRoomQueryerMockRecorder) Find(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRoomQueryer)(nil).Find), arg0, arg1)
}

// FindAllByUserID mocks base method
func (m *MockRoomQueryer) FindAllByUserID(arg0 context.Context, arg1 uint64) ([]domain.Room, error) {
	ret := m.ctrl.Call(m, "FindAllByUserID", arg0, arg1)
	ret0, _ := ret[0].([]domain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByUserID indicates an expected call of FindAllByUserID
func (mr *MockRoomQueryerMockRecorder) FindAllByUserID(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByUserID", reflect.TypeOf((*MockRoomQueryer)(nil).FindAllByUserID), arg0, arg1)
}

// FindRoomInfo mocks base method
func (m *MockRoomQueryer) FindRoomInfo(arg0 context.Context, arg1, arg2 uint64) (*queried.RoomInfo, error) {
	ret := m.ctrl.Call(m, "FindRoomInfo", arg0, arg1, arg2)
	ret0, _ := ret[0].(*queried.RoomInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRoomInfo indicates an expected call of FindRoomInfo
func (mr *MockRoomQueryerMockRecorder) FindRoomInfo(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRoomInfo", reflect.TypeOf((*MockRoomQueryer)(nil).FindRoomInfo), arg0, arg1, arg2)
}

// MockMessageQueryer is a mock of MessageQueryer interface
type MockMessageQueryer struct {
	ctrl     *gomock.Controller
	recorder *MockMessageQueryerMockRecorder
}

// MockMessageQueryerMockRecorder is the mock recorder for MockMessageQueryer
type MockMessageQueryerMockRecorder struct {
	mock *MockMessageQueryer
}

// NewMockMessageQueryer creates a new mock instance
func NewMockMessageQueryer(ctrl *gomock.Controller) *MockMessageQueryer {
	mock := &MockMessageQueryer{ctrl: ctrl}
	mock.recorder = &MockMessageQueryerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMessageQueryer) EXPECT() *MockMessageQueryerMockRecorder {
	return m.recorder
}

// FindRoomMessagesOrderByLatest mocks base method
func (m *MockMessageQueryer) FindRoomMessagesOrderByLatest(arg0 context.Context, arg1 uint64, arg2 time.Time, arg3 int) ([]domain.Message, error) {
	ret := m.ctrl.Call(m, "FindRoomMessagesOrderByLatest", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]domain.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRoomMessagesOrderByLatest indicates an expected call of FindRoomMessagesOrderByLatest
func (mr *MockMessageQueryerMockRecorder) FindRoomMessagesOrderByLatest(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRoomMessagesOrderByLatest", reflect.TypeOf((*MockMessageQueryer)(nil).FindRoomMessagesOrderByLatest), arg0, arg1, arg2, arg3)
}

// MockEventQueryer is a mock of EventQueryer interface
type MockEventQueryer struct {
	ctrl     *gomock.Controller
	recorder *MockEventQueryerMockRecorder
}

// MockEventQueryerMockRecorder is the mock recorder for MockEventQueryer
type MockEventQueryerMockRecorder struct {
	mock *MockEventQueryer
}

// NewMockEventQueryer creates a new mock instance
func NewMockEventQueryer(ctrl *gomock.Controller) *MockEventQueryer {
	mock := &MockEventQueryer{ctrl: ctrl}
	mock.recorder = &MockEventQueryerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEventQueryer) EXPECT() *MockEventQueryerMockRecorder {
	return m.recorder
}

// FindAllByStreamID mocks base method
func (m *MockEventQueryer) FindAllByStreamID(arg0 context.Context, arg1 event.StreamID, arg2 time.Time, arg3 int) ([]event.Event, error) {
	ret := m.ctrl.Call(m, "FindAllByStreamID", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]event.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByStreamID indicates an expected call of FindAllByStreamID
func (mr *MockEventQueryerMockRecorder) FindAllByStreamID(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByStreamID", reflect.TypeOf((*MockEventQueryer)(nil).FindAllByStreamID), arg0, arg1, arg2, arg3)
}

// FindAllByTimeCursor mocks base method
func (m *MockEventQueryer) FindAllByTimeCursor(arg0 context.Context, arg1 time.Time, arg2 int) ([]event.Event, error) {
	ret := m.ctrl.Call(m, "FindAllByTimeCursor", arg0, arg1, arg2)
	ret0, _ := ret[0].([]event.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByTimeCursor indicates an expected call of FindAllByTimeCursor
func (mr *MockEventQueryerMockRecorder) FindAllByTimeCursor(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByTimeCursor", reflect.TypeOf((*MockEventQueryer)(nil).FindAllByTimeCursor), arg0, arg1, arg2)
}
