// Code generated by "stringer -type EventType"; DO NOT EDIT.

package domain

import "fmt"

const _EventType_name = "EventNoneEventErrorRaisedEventUserCreatedEventUserDeletedEventUserAddedFriendEventRoomCreatedEventRoomDeletedEventRoomAddedMemberEventRoomRemoveMemberEventRoomPostedMessageEventRoomUpdatedMessageEventRoomDeletedMessageEventMessageCreatedEventMessageReadByUserEventActiveClientActivatedEventActiveClientInactivated"

var _EventType_index = [...]uint16{0, 9, 25, 41, 57, 77, 93, 109, 129, 150, 172, 195, 218, 237, 259, 285, 313}

func (i EventType) String() string {
	if i >= EventType(len(_EventType_index)-1) {
		return fmt.Sprintf("EventType(%d)", i)
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
