// Code generated by "stringer -type EventType"; DO NOT EDIT.

package domain

import "fmt"

const _EventType_name = "EventNoneEventUserCreatedEventUserDeletedEventUserAddedFriendEventRoomCreatedEventRoomDeletedEventRoomAddedMemberEventRoomRemoveMemberEventRoomPostedMessageEventRoomUpdatedMessageEventRoomDeletedMessage"

var _EventType_index = [...]uint8{0, 9, 25, 41, 61, 77, 93, 113, 134, 156, 179, 202}

func (i EventType) String() string {
	if i >= EventType(len(_EventType_index)-1) {
		return fmt.Sprintf("EventType(%d)", i)
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
